### ISSUE TITLE
When exiting a round with the input box visible, the input box persists through the start of a new game 

### ISSUE THREAD

**Issue by glenn-sun** [Math-Game-MCA/Math-Game---Lua#1]
![image](https://user-images.githubusercontent.com/21298521/28349011-4c2db59a-6c0e-11e7-8acb-6a90a180cced.png)

To reproduce:
* Start a game
* Put 2 numbers and an operator, do not solve
* Exit game
* Start a new game

**Comment by lucentfong** [comment]
find where the exit button returns back to the main menu. when it exits, send a message to solve,gui telling it to hide. should fix it. make sure you resolve any variables in solve if necessary when the message is received.

**Comment by lucentfong** [comment]
Fixed
